import type { MetadataRoute } from 'next'
import { DEFAULT_LOCALE } from '@i18n/config'
import { localePath } from '@i18n/pathname'
import { ROUTES } from '@constants/routes'
import { BRAND, NEUTRAL } from '@styles/tokens'

export default function manifest(): MetadataRoute.Manifest {
  const startUrl = localePath(DEFAULT_LOCALE, ROUTES.home)

  return {
    // Stable identity. Not `start_url`: changing the default landing page must
    // not install a second copy of the app next to the first.
    id: '/',
    name: 'Bookie',
    short_name: 'Bookie',
    description: 'Your Booking Platform Forever',
    lang: DEFAULT_LOCALE,
    dir: 'ltr',
    // localePrefix is 'always', so '/' is not a document — it 307s to /<locale>.
    // A start_url that is itself a redirect can make the browser re-enter the
    // page after reading the manifest.
    start_url: startUrl,
    scope: '/',
    display: 'standalone',
    display_override: ['standalone', 'minimal-ui', 'browser'],
    // Reuse the existing window when a home-screen tap or captured link fires,
    // rather than stacking a second standalone instance.
    launch_handler: { client_mode: ['navigate-existing', 'auto'] },
    background_color: NEUTRAL[0],
    theme_color: BRAND[900],
    categories: ['lifestyle', 'business'],
    // Generated by src/app/icon.tsx and src/app/icon-maskable/route.tsx.
    // `purpose` cannot be combined in Next's Manifest type — two entries.
    // One 512px source is enough for installability; browsers downscale.
    icons: [
      { src: '/icon', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icon-maskable', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
    shortcuts: [
      {
        name: 'Explore providers',
        short_name: 'Explore',
        url: localePath(DEFAULT_LOCALE, ROUTES.providers),
        icons: [{ src: '/icon', sizes: '512x512', type: 'image/png' }],
      },
      {
        name: 'Sign in',
        short_name: 'Sign in',
        url: localePath(DEFAULT_LOCALE, ROUTES.signIn),
        icons: [{ src: '/icon', sizes: '512x512', type: 'image/png' }],
      },
    ],
  }
}
