import type { MetadataRoute } from 'next'
import { BRAND, NEUTRAL } from '@styles/tokens'

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Bookie',
    short_name: 'Bookie',
    description: 'Your Booking Platform Forever',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait-primary',
    background_color: NEUTRAL[0],
    theme_color: BRAND[900],
    // Generated by src/app/icon.tsx. One 512px source is enough for
    // installability; browsers downscale from the largest icon available.
    icons: [{ src: '/icon', sizes: '512x512', type: 'image/png' }],
  }
}
