import type { MetadataRoute } from 'next'
import { DEFAULT_LOCALE } from '@i18n/config'
import { BRAND, NEUTRAL } from '@styles/tokens'

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Bookie',
    short_name: 'Bookie',
    description: 'Your Booking Platform Forever',
    // localePrefix is 'always', so '/' is not a document — it 307s to /<locale>.
    // A start_url that is itself a redirect can make the browser re-enter the
    // page after reading the manifest.
    start_url: `/${DEFAULT_LOCALE}`,
    scope: '/',
    display: 'standalone',
    orientation: 'portrait-primary',
    background_color: NEUTRAL[0],
    theme_color: BRAND[900],
    // Generated by src/app/icon.tsx. One 512px source is enough for
    // installability; browsers downscale from the largest icon available.
    icons: [{ src: '/icon', sizes: '512x512', type: 'image/png' }],
  }
}
